import React, { Component } from 'react';
import { Grid, Button } from 'semantic-ui-react';
import PostList from '../PostList/PostList';
import NewPost from './NewPost';

const postsDashboard = [
  {
    id: '1',
    title: 'Java',
    category: 'tech',
    selectedTag:'java',
    description:'This is generally referred as JVM. Before, we discuss about JVM lets see the phases of program execution. Phases are as follows: we write the program, then we compile the program and at last we run the program. Writing of the program is of course done by java programmer like you and me.Compilation of program is done by javac compiler, javac is the primary java compiler included in java development kit (JDK). It takes java program as input and generates java bytecode as output. In third phase, JVM executes the bytecode generated by compiler. This is called program run phase.',
    postedBy: 'Aakarsh',
    postPhotoURL: 'https://robohash.org/aaka',
    followers: [
      {
        id: 'b',
        name: 'Teja',
        photoURL: 'https://robohash.org/as'
      }
    ]
  },
  {
    id: '2',
    title: 'Placement-Oracle',
    category: 'placementInfo',
    description:
      'Oracle is one of the largest vendors in the enterprise IT market and the shorthand name of its flagship product, a relational database management system (RDBMS) that\'s formally called Oracle Database. The database software sits at the center of many corporate IT environments, supporting a mix of transaction processing, business intelligence and analytics applications.',
    postedBy: 'Teja',
    postPhotoURL: 'https://robohash.org/te',
    followers: [
      {
        id: 'b',
        name: 'Aakarsh',
        photoURL: 'https://robohash.org/aas'
      }
    ]
  },
  {
    id: '3',
    title: 'Python',
    category: 'tech',
    description:'This is generally referred as JVM. Before, we discuss about JVM lets see the phases of program execution. Phases are as follows: we write the program, then we compile the program and at last we run the program. Writing of the program is of course done by java programmer like you and me.Compilation of program is done by javac compiler, javac is the primary java compiler included in java development kit (JDK). It takes java program as input and generates java bytecode as output. In third phase, JVM executes the bytecode generated by compiler. This is called program run phase.',
    postedBy: 'Mani',
    postPhotoURL: 'https://robohash.org/adf',
    followers: [
      {
        id: 'b',
        name: 'Teja',
        photoURL: 'https://robohash.org/as'
      },
      {
        id: 'a',
        name: 'Aakarsh',
        photoURL: 'https://robohash.org/asf'
      }
    ]
  }
];

class PostDashboard extends Component {
  state = {
    posts: postsDashboard,
    visible:false
  };
handleCreatePost = (event) => {
  event.postPhotoURL = './user.png';
  const updatedPosts = [...this.state.posts,event];
  this.setState({
    posts:updatedPosts,
    visible:false
  });
}
  render() {
    return (
      <Grid>
        <Grid.Column width={14}>
          <PostList posts={this.state.posts} />
        </Grid.Column>
        <Grid.Column width={2}>
          <NewPost createPost={this.handleCreatePost}/>
        </Grid.Column>
      </Grid>
    );
  }
}

export default PostDashboard;
